/*********************************************
 * Author:				Ahmed Samy
 * Creation Data:		11 Jun, 2024
 * Version:				v1.0
 * Compiler:			GNU ARM-GCC
 * Controller:			STM32F401CCU6
 * Layer:				MCAL
 ********************************************/
/*********************************************
 * Version	  Date				  Author				  Description
 * v1.0		  11 Jun, 2024		  Ahmed Samy		  	Initial Creation
*********************************************/

#ifndef  EXTI_CONFIG_H
#define  EXTI_CONFIG_H


/* EXTI ENABLES
options:
EXTI_ENABLE
EXTI_DISABLE
*/
#define MEXTI_EXTI0_ENABLE      EXTI_ENABLE
#define MEXTI_EXTI1_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI2_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI3_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI4_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI5_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI6_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI7_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI8_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI9_ENABLE      EXTI_DISABLE
#define MEXTI_EXTI10_ENABLE     EXTI_DISABLE
#define MEXTI_EXTI11_ENABLE     EXTI_DISABLE
#define MEXTI_EXTI12_ENABLE     EXTI_DISABLE
#define MEXTI_EXTI13_ENABLE     EXTI_DISABLE
#define MEXTI_EXTI14_ENABLE     EXTI_DISABLE
#define MEXTI_EXTI15_ENABLE     EXTI_DISABLE

/* CHOOSE PORT
options:
SYSCFG_EXTICR_PA
SYSCFG_EXTICR_PB
SYSCFG_EXTICR_PC
*/

#define MEXTI_EXTI0_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI1_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI2_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI3_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI4_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI5_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI6_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI7_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI8_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI9_PORT        SYSCFG_EXTICR_PA
#define MEXTI_EXTI10_PORT       SYSCFG_EXTICR_PA
#define MEXTI_EXTI11_PORT       SYSCFG_EXTICR_PA
#define MEXTI_EXTI12_PORT       SYSCFG_EXTICR_PA
#define MEXTI_EXTI13_PORT       SYSCFG_EXTICR_PA
#define MEXTI_EXTI14_PORT       SYSCFG_EXTICR_PA
#define MEXTI_EXTI15_PORT       SYSCFG_EXTICR_PA

/* CHOOSE SENSITIVITY
options:
MEXTI_RISING
MEXTI_FALLING
MEXTI_ONCHANGE
*/
#define MEXTI_EXTI0_SENS        MEXTI_FALLING        
#define MEXTI_EXTI1_SENS        MEXTI_FALLING
#define MEXTI_EXTI2_SENS        MEXTI_FALLING
#define MEXTI_EXTI3_SENS        MEXTI_FALLING
#define MEXTI_EXTI4_SENS        MEXTI_FALLING
#define MEXTI_EXTI5_SENS        MEXTI_FALLING
#define MEXTI_EXTI6_SENS        MEXTI_FALLING
#define MEXTI_EXTI7_SENS        MEXTI_FALLING
#define MEXTI_EXTI8_SENS        MEXTI_FALLING
#define MEXTI_EXTI9_SENS        MEXTI_FALLING
#define MEXTI_EXTI10_SENS       MEXTI_FALLING
#define MEXTI_EXTI11_SENS       MEXTI_FALLING
#define MEXTI_EXTI12_SENS       MEXTI_FALLING
#define MEXTI_EXTI13_SENS       MEXTI_FALLING
#define MEXTI_EXTI14_SENS       MEXTI_FALLING
#define MEXTI_EXTI15_SENS       MEXTI_FALLING

#endif
